---
spring:
  profiles: default
  ### General Information ###
  application:
      name: cf-service-broker-postgresql
  ### Security ###
  ssl:
    acceptselfsigned: true
  ### Cloud Config ###
  #  cloud:
  #    config:
  #      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

  ### Deployment ###
  #### Docker ####
  rabbitmq:
    host:
    port:
    username:
    password:
    # virtual-host:
    template:
      reply-timeout: 120000

### General Information ###
info:
  app:
    name: PostgreSQL Service Broker
    description: PostgreSQL Service Broker for Cloud Foundry Service Deployments
    version: 0.1-RC

server:
  port: ${SERVER_PORT:8080}

### Logging ###
logging:
  file: ${LOG_FILE:cf-service-broker-postgresql.log}
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

### Service ###
backend:
  ports:
    default:
  connection:
    timeouts:

### Persistence ###
#### Redis ####
redis:
  host:
  port:
  password:
  timeout: 5
  retries: 20
  param:

### Service Key Generation ###
#### HAProxy ####
haproxy:
  uri:
  auth:
    token:

### Deployment ###
deployment:
  repo:
    main:
      uri:
    monit:
      uri:
    service:
      uri:


### Deployment ###
#### Docker ####
docker:
  imageName:
  offset:
  host:
  port:
  portRange:
    start:
    end:
  ssl:
    enabled: false
  syslogAddress:

#### OpenStack ####
openstack:
  endpoint:
  username:
  password:
  tenantId:
  networkId:
  subnetId:
  imageId:
  keypair:
  log_host:
  log_port:
  cinder:
    az:
